# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: annotationMaker-1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bioconda::samtools=1.11
  - bioconda::star=2.7.6a
  - bioconda::hisat2=2.2.1
  - bioconda::bowtie2=2.4.2
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.23.8
  - bioconda::bedtools=2.29.2
  - bioconda::ucsc-gtftogenepred=377
  - bioconda::ucsc-genepredtobed=377
  - bioconda::ucsc-gff3togenepred=377
  - bioconda::ucsc-fasize=377
  - bioconda::gffread=0.12.1
  - conda-forge::r-base=4.0.3
  - bioconda::bioconductor-genomicfeatures=1.40.0
  - bioconda::bioconductor-rtracklayer=1.48.0
  - bioconda::kallisto=0.46.2
  - bioconda::bustools=0.40.0
